name = "doctorcare"
main = "apps/web/.open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "apps/web/.open-next/assets"
binding = "ASSETS"

# Service Binding to internal API Worker
# Uncomment once doctorcare-api is deployed:
# [[services]]
# binding = "API_SERVICE"
# service = "doctorcare-api"


[vars]
NEXT_PUBLIC_APP_NAME = "DoctorCare"
NEXT_PUBLIC_API_URL = "https://api.yourhospital.com"
NEXT_PUBLIC_APPWRITE_ENDPOINT = "https://cloud.appwrite.io/v1"
NEXT_PUBLIC_APPWRITE_PROJECT_A_ID = "doctorcare-operational-prod"
